import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Footer } from './components/Footer'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {

  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className='w-full h-full flex flex-col justify-between'>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
