import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { Header } from '../components/Header'

export const metadata: Metadata = {
    title: 'Profile',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: ReactNode
}) {
    return (
        <>
            <Header />
            {children}
        </>
    )
}
